@budget = http://localhost:8082/api/budgets

GET {{budget}}/view
Authorization: Basic Sannith:12345
# Content-Type: application/json   

# DELETE  {{budget}}/delete/1

# Content-Type: application/json

# {

# }
# DELETE  {{budget}}/delete/2

# Content-Type: application/json

# {

# }

# POST {{budget}}/new
# Content-Type: application/json

# {
    
#     "type": "hotelbusiness",
#     "income": 50000
   
# }

# POST {{budget}}/new
# Content-Type: application/json

# {
#     "type": "trading",
#     "income": 2000
    
# }

# PUT  {{budget}}/update/1
# Content-Type: application/json

# {
#     "type":"hotelbusiness",
#     "income": 50000,
#     "date": "2023-10-01"
    
# }
# POST {{budget}}/new
# Content-Type: application/json

# {
    
#     "type": "hotelbusiness",
#     "income": 50000
   
# }

# GET {{budget}}/low-budget-alert
# Content-Type: application/json
###
GET {{budget}}/summary/2
# Content-Type: application/json

### 
@base = http://localhost:8082/api/expenses
GET {{base}}/view
# Content-Type: application/json

# {
# }

# POST  {{base}}/new
# Content-Type: application/json

# {
#     "type": "eductaion",
#     "amount": 20001.0,
#     "budgetId": 2
# }

# POST  {{base}}/new
# Content-Type: application/json

# {
#     "type": "eductaion",
#     "amount": 8977.0,
#     "budgetId": 1
# }

# POST  {{base}}/new
# Content-Type: application/json

# {
#     "type": "eductaion",
#     "amount": 150.0,
#     "budgetId": 2
# }

# POST  {{base}}/new
# Content-Type: application/json

# {
#     "type": "eductaion",
#     "amount": 150.0,
#     "budgetId": 1
# }

# POST  {{base}}/new
# Content-Type: application/json

# {
#     "type": "eductaion",
#     "amount": 20000.0,
#     "budgetId": 3
# }


# PUT {{base}}/update/4
# Content-Type: application/json

# {
#     "type": "eductaion",
#     "amount": 150.0,
#     "budgetId": 3
# }

# PUT {{base}}/update/3
# Content-Type: application/json

# {
#     "type": "food",
#     "amount": 1000,
#     "budgetId": 4
# }

# PUT {{base}}/update/2
# Content-Type: application/json

# {
#     "type": "food",
#     "amount": 300.0,
#     "budgetId": 4
# }



# DELETE  {{base}}/delete/3
# Content-Type: application/json

# {
# }